name: Update database types
on:
    push:
        branches: [main]
        paths:
            - '*.sql'
    schedule:
        - cron: '0 12 * * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: lyqht/generate-supabase-db-types-github-action@main
              with:
                  SUPABASE_REF_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
                  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
                  DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
                  OUTPUT_PATH: db.types.ts
